language: pythons

python:
  - "2.7"

# install dependencies
install:
  - sudo pip install --upgrade pip
  - sudo pip install -r requirements.txt
  - sudo pip install pytest
  - sudo pip install coverage
  - sudo pip install pytest-cov
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - ./cc-test-reporter before-build

# run tests with coverage
script:
  - pytest --cov=.

after_script:
  - coverage xml
  - ./cc-test-reporter after-build --coverage-input-type=coverage.py --exit-code $TRAVIS_TEST_RESULT
